[package]
name = "akamai-deob-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
swc_common = "0.40"
swc_ecma_ast = "0.121"
swc_ecma_visit = "0.107"
swc_ecma_parser = "0.152"
swc_ecma_transforms = "0.243"
swc_ecma_codegen = "0.158"
oxc_allocator = "0.30.5"
oxc_ast = "0.30.5"
oxc_codegen = "0.30.5"
oxc_mangler = "0.30.5"
oxc_parser = "0.30.5"
oxc_semantic = "0.30.5"
oxc_span = "0.30.5"
oxc_syntax = "0.30.5"
oxc_traverse = "0.30.5"
oxc_minifier = "0.30.5"

cow-utils = "0.1.3"
num-bigint = "0.4.6"
num-traits = "0.2.19"

pico-args = "0.5.0"
