[package]
name = "akamai_deob_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
oxc_allocator = "0.30.5"
oxc_ast = "0.30.5"
oxc_codegen = "0.30.5"
oxc_mangler = "0.30.5"
oxc_parser = "0.30.5"
oxc_semantic = "0.30.5"
oxc_span = "0.30.5"
oxc_syntax = "0.30.5"
oxc_traverse = "0.30.5"
oxc_minifier = "0.30.5"

cow-utils = "0.1.3"
num-bigint = "0.4.6"
num-traits = "0.2.19"

pico-args = "0.5.0"
